# Generated by Django 5.0.4 on 2024-05-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('pk_absence_type', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tb_absence_type',
            },
        ),
        migrations.CreateModel(
            name='ClassSetting',
            fields=[
                ('pk_class_setting', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('edited', models.DateTimeField()),
                ('skill', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_class_setting',
            },
        ),
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('pk_note_type', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tb_note_type',
            },
        ),
        migrations.CreateModel(
            name='PedagogicalSetting',
            fields=[
                ('pk_pedagogical_setting', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('edited', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_pedagogical_setting',
            },
        ),
        migrations.CreateModel(
            name='SchoolGrade',
            fields=[
                ('pk_school_grade', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tb_school_grade',
            },
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('pk_school_level', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tb_school_level',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('pk_school_year', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('year', models.CharField(max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField()),
                ('skill', models.IntegerField()),
                ('total_grade', models.FloatField()),
                ('average_grade', models.FloatField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_school_year',
            },
        ),
        migrations.CreateModel(
            name='SchoolYearDate',
            fields=[
                ('pk_school_year_date', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('init_date', models.DateField()),
                ('final_date', models.DateField()),
                ('grade', models.FloatField()),
            ],
            options={
                'db_table': 'tb_school_year_date',
            },
        ),
        migrations.CreateModel(
            name='SchoolYearSkill',
            fields=[
                ('pk_school_year_skill', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'tb_school_level_skill',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('pk_shift', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tb_shift',
            },
        ),
        migrations.CreateModel(
            name='SkillGrade',
            fields=[
                ('pk_skill_grade', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('grade_1', models.FloatField(default=0.0)),
                ('grade_2', models.FloatField(default=0.0)),
                ('grade_3', models.FloatField(default=0.0)),
                ('grade_4', models.FloatField(default=0.0)),
                ('grade_5', models.FloatField(default=0.0)),
                ('edited', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_skill_grade',
            },
        ),
        migrations.CreateModel(
            name='SkillSettings',
            fields=[
                ('pk_skill_setting', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('label_name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_skill',
            },
        ),
        migrations.CreateModel(
            name='StudentAbcense',
            fields=[
                ('pk_student_abcense', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('abcense', models.IntegerField(default=100)),
                ('edited', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_student_abcense',
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('pk_student_class', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_student_class',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('pk_subject', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subject_code', models.IntegerField(unique=True)),
                ('subject_name', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_subject',
            },
        ),
        migrations.CreateModel(
            name='SubjectArea',
            fields=[
                ('pk_subject_area', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_subject_area',
            },
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('pk_subject_grade', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('grade_1', models.FloatField(default=0.0)),
                ('grade_2', models.FloatField(default=0.0)),
                ('grade_3', models.FloatField(default=0.0)),
                ('grade_4', models.FloatField(default=0.0)),
                ('grade_5', models.FloatField(default=0.0)),
                ('edited', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_subject_grade',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('pk_term_type', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tb_term',
            },
        ),
        migrations.CreateModel(
            name='TermType',
            fields=[
                ('pk_term_type', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tb_term_type',
            },
        ),
    ]
