# Generated by Django 5.0.4 on 2024-05-01 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('register', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classsetting',
            name='fk_campus',
            field=models.ForeignKey(db_column='fk_campus', on_delete=django.db.models.deletion.DO_NOTHING, to='register.campus'),
        ),
        migrations.AddField(
            model_name='pedagogicalsetting',
            name='fk_class_setting',
            field=models.ForeignKey(db_column='fk_class_setting', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.classsetting'),
        ),
        migrations.AddField(
            model_name='pedagogicalsetting',
            name='fk_employee_user',
            field=models.ForeignKey(db_column='fk_employee_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsetting',
            name='fk_school_grade',
            field=models.ForeignKey(db_column='fk_school_grade', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.schoolgrade'),
        ),
        migrations.AddField(
            model_name='schoolgrade',
            name='fk_school_level',
            field=models.ForeignKey(db_column='fk_school_level', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.schoollevel'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='fk_campus',
            field=models.ForeignKey(db_column='fk_campus', on_delete=django.db.models.deletion.DO_NOTHING, to='register.campus'),
        ),
        migrations.AddField(
            model_name='classsetting',
            name='fk_school_year',
            field=models.ForeignKey(db_column='fk_school_year', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.schoolyear'),
        ),
        migrations.AddField(
            model_name='schoolyeardate',
            name='fk_school_year',
            field=models.ForeignKey(db_column='fk_school_year', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.schoolyear'),
        ),
        migrations.AddField(
            model_name='schoolyearskill',
            name='fk_school_year',
            field=models.ForeignKey(db_column='fk_school_year', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.schoolyear'),
        ),
        migrations.AddField(
            model_name='classsetting',
            name='fk_shift',
            field=models.ForeignKey(db_column='fk_shift', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.shift'),
        ),
        migrations.AddField(
            model_name='skillgrade',
            name='fk_class',
            field=models.ForeignKey(db_column='fk_class', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.classsetting'),
        ),
        migrations.AddField(
            model_name='skillgrade',
            name='fk_student_user',
            field=models.ForeignKey(db_column='fk_student_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillsettings',
            name='fk_campus',
            field=models.ForeignKey(db_column='fk_campus', on_delete=django.db.models.deletion.DO_NOTHING, to='register.campus'),
        ),
        migrations.AddField(
            model_name='skillgrade',
            name='fk_skill',
            field=models.ForeignKey(db_column='fk_skill', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.skillsettings'),
        ),
        migrations.AddField(
            model_name='schoolyearskill',
            name='fk_skill',
            field=models.ForeignKey(db_column='fk_skill', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.skillsettings'),
        ),
        migrations.AddField(
            model_name='studentabcense',
            name='fk_class',
            field=models.ForeignKey(db_column='fk_class', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.classsetting'),
        ),
        migrations.AddField(
            model_name='studentabcense',
            name='fk_student_user',
            field=models.ForeignKey(db_column='fk_student_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='fk_class_setting',
            field=models.ForeignKey(db_column='fk_class_setting', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.classsetting'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='fk_student_user',
            field=models.ForeignKey(db_column='fk_student_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='fk_campus',
            field=models.ForeignKey(db_column='fk_campus', on_delete=django.db.models.deletion.DO_NOTHING, to='register.campus'),
        ),
        migrations.AddField(
            model_name='studentabcense',
            name='fk_subject',
            field=models.ForeignKey(db_column='fk_subject', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.subject'),
        ),
        migrations.AddField(
            model_name='skillgrade',
            name='fk_subject',
            field=models.ForeignKey(db_column='fk_subject', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.subject'),
        ),
        migrations.AddField(
            model_name='pedagogicalsetting',
            name='fk_subject',
            field=models.ForeignKey(db_column='fk_subject', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.subject'),
        ),
        migrations.AddField(
            model_name='subjectarea',
            name='fk_campus',
            field=models.ForeignKey(db_column='fk_campus', on_delete=django.db.models.deletion.DO_NOTHING, to='register.campus'),
        ),
        migrations.AddField(
            model_name='subject',
            name='fk_subject_area',
            field=models.ForeignKey(db_column='fk_subject_area', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.subjectarea'),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='fk_class',
            field=models.ForeignKey(db_column='fk_class', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.classsetting'),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='fk_student_user',
            field=models.ForeignKey(db_column='fk_student_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='fk_subject',
            field=models.ForeignKey(db_column='fk_subject', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.subject'),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='fk_term',
            field=models.ForeignKey(db_column='fk_term', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.term'),
        ),
        migrations.AddField(
            model_name='studentabcense',
            name='fk_term',
            field=models.ForeignKey(db_column='fk_term', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.term'),
        ),
        migrations.AddField(
            model_name='skillgrade',
            name='fk_term',
            field=models.ForeignKey(db_column='fk_term', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.term'),
        ),
        migrations.AddField(
            model_name='schoolyeardate',
            name='fk_term',
            field=models.ForeignKey(db_column='fk_term', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.term'),
        ),
        migrations.AddField(
            model_name='term',
            name='fk_term_type',
            field=models.ForeignKey(db_column='fk_term_type', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.termtype'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='fk_term_type',
            field=models.ForeignKey(db_column='fk_term_type', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.termtype'),
        ),
    ]
