# Generated by Django 5.0.4 on 2024-05-01 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPresence',
            fields=[
                ('pk_student_presence', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('presence', models.IntegerField(default=100)),
                ('date_presence', models.DateField()),
                ('fk_class', models.ForeignKey(db_column='fk_class', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.classsetting')),
                ('fk_student_user', models.ForeignKey(db_column='fk_student_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('fk_subject', models.ForeignKey(db_column='fk_subject', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.subject')),
                ('fk_term', models.ForeignKey(db_column='fk_term', on_delete=django.db.models.deletion.DO_NOTHING, to='academic.term')),
            ],
            options={
                'db_table': 'tb_student_presence',
            },
        ),
        migrations.DeleteModel(
            name='StudentAbcense',
        ),
    ]
