# Generated by Django 5.0.4 on 2024-05-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_studentpresence_delete_studentabcense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsetting',
            name='skill',
        ),
    ]
