# Generated by Django 5.0.4 on 2024-05-21 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_classsetting_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedagogicalsetting',
            name='fk_class_setting',
            field=models.ForeignKey(db_column='fk_class_setting', on_delete=django.db.models.deletion.CASCADE, to='academic.classsetting'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='fk_class_setting',
            field=models.ForeignKey(db_column='fk_class_setting', on_delete=django.db.models.deletion.CASCADE, to='academic.classsetting'),
        ),
    ]
