# Generated by Django 5.0.4 on 2024-05-24 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_pedagogicalsetting_fk_class_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolgrade',
            name='fk_school_level',
            field=models.ForeignKey(db_column='fk_school_level', on_delete=django.db.models.deletion.CASCADE, to='academic.schoollevel'),
        ),
        migrations.AlterField(
            model_name='schoolyeardate',
            name='fk_school_year',
            field=models.ForeignKey(db_column='fk_school_year', on_delete=django.db.models.deletion.CASCADE, to='academic.schoolyear'),
        ),
        migrations.AlterField(
            model_name='schoolyearskill',
            name='fk_school_year',
            field=models.ForeignKey(db_column='fk_school_year', on_delete=django.db.models.deletion.CASCADE, to='academic.schoolyear'),
        ),
        migrations.AlterField(
            model_name='skillgrade',
            name='fk_class',
            field=models.ForeignKey(db_column='fk_class', on_delete=django.db.models.deletion.CASCADE, to='academic.classsetting'),
        ),
        migrations.AlterField(
            model_name='studentpresence',
            name='fk_class',
            field=models.ForeignKey(db_column='fk_class', on_delete=django.db.models.deletion.CASCADE, to='academic.classsetting'),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='fk_class',
            field=models.ForeignKey(db_column='fk_class', on_delete=django.db.models.deletion.CASCADE, to='academic.classsetting'),
        ),
        migrations.AlterField(
            model_name='term',
            name='fk_term_type',
            field=models.ForeignKey(db_column='fk_term_type', on_delete=django.db.models.deletion.CASCADE, to='academic.termtype'),
        ),
    ]
