# Generated by Django 5.0.4 on 2024-06-26 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DRCTInternalNote',
            fields=[
                ('pk_drct_internal_note', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('drct_single_attach', models.CharField(max_length=30)),
                ('ctdr_deadline', models.DateField()),
                ('ctdr_student_deadline', models.DateField()),
                ('ctdr_cal_statement', models.IntegerField(null=True)),
                ('ctdr_cmdt_statement', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('fk_campus', models.ForeignKey(db_column='fk_campus', on_delete=django.db.models.deletion.DO_NOTHING, to='register.campus')),
                ('fk_reporter', models.ForeignKey(db_column='fk_reporter', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_drct_internal_note',
            },
        ),
        migrations.CreateModel(
            name='DRCTComment',
            fields=[
                ('pk_drct_comment', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('fk_user', models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('fk_drct_internal_note', models.ForeignKey(db_column='fk_drct_internal_note', on_delete=django.db.models.deletion.CASCADE, to='ct_requests.drctinternalnote')),
            ],
            options={
                'db_table': 'tb_drct_comment',
            },
        ),
        migrations.CreateModel(
            name='DRCTRegulament',
            fields=[
                ('pk_drct_regulament', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('regulament', models.CharField(max_length=30)),
                ('fk_drct_internal_note', models.ForeignKey(db_column='fk_drct_internal_note', on_delete=django.db.models.deletion.CASCADE, to='ct_requests.drctinternalnote')),
            ],
            options={
                'db_table': 'tb_drct_regulament',
            },
        ),
        migrations.CreateModel(
            name='DRCTStudentInternalNote',
            fields=[
                ('pk_drct_student_internal_note', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fk_drct_internal_note', models.ForeignKey(db_column='fk_drct_internal_note', on_delete=django.db.models.deletion.CASCADE, to='ct_requests.drctinternalnote')),
                ('fk_student', models.ForeignKey(db_column='fk_student', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_drct_student_internal_note',
            },
        ),
    ]
