# Generated by Django 5.0.4 on 2024-05-18 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DRCTChapter',
            fields=[
                ('pk_drct_chapter', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_drct_chapter',
            },
        ),
        migrations.CreateModel(
            name='DRCTParagraph',
            fields=[
                ('pk_drct_paragraph', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'tb_drct_paragraph',
            },
        ),
        migrations.CreateModel(
            name='DRCTPenalty',
            fields=[
                ('pk_drct_penalty', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=320)),
            ],
            options={
                'db_table': 'tb_drct_penalty',
            },
        ),
        migrations.CreateModel(
            name='DRCTSeverity',
            fields=[
                ('pk_drct_severity', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_drct_severity',
            },
        ),
        migrations.CreateModel(
            name='DRCTRequest',
            fields=[
                ('pk_drct_request', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('status', models.IntegerField()),
                ('fk_campus', models.ForeignKey(db_column='fk_campus', on_delete=django.db.models.deletion.DO_NOTHING, to='register.campus')),
                ('fk_drct_chapter', models.ForeignKey(db_column='fk_drct_chapter', on_delete=django.db.models.deletion.DO_NOTHING, to='ct_requests.drctchapter')),
                ('fk_drct_paragraph', models.ForeignKey(db_column='fk_drct_paragraph', on_delete=django.db.models.deletion.DO_NOTHING, to='ct_requests.drctparagraph')),
                ('fk_drct_penalty', models.ForeignKey(db_column='fk_drct_penalty', on_delete=django.db.models.deletion.DO_NOTHING, to='ct_requests.drctpenalty')),
                ('fk_reporter', models.ForeignKey(db_column='fk_reporter', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_drct_request',
            },
        ),
        migrations.CreateModel(
            name='DRCTComment',
            fields=[
                ('pk_drct_comment', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('fk_user', models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('fk_drct_request', models.ForeignKey(db_column='fk_drct_request', on_delete=django.db.models.deletion.DO_NOTHING, to='ct_requests.drctrequest')),
            ],
            options={
                'db_table': 'tb_drct_comment',
            },
        ),
        migrations.CreateModel(
            name='DRCTSection',
            fields=[
                ('pk_drct_section', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('fk_drct_chapter', models.ForeignKey(db_column='fk_drct_chapter', on_delete=django.db.models.deletion.DO_NOTHING, to='ct_requests.drctchapter')),
            ],
            options={
                'db_table': 'tb_drct_section',
            },
        ),
        migrations.AddField(
            model_name='drctrequest',
            name='fk_drct_section',
            field=models.ForeignKey(db_column='fk_drct_section', on_delete=django.db.models.deletion.DO_NOTHING, to='ct_requests.drctsection'),
        ),
        migrations.AddField(
            model_name='drctparagraph',
            name='fk_drct_section',
            field=models.ForeignKey(db_column='fk_drct_section', on_delete=django.db.models.deletion.DO_NOTHING, to='ct_requests.drctsection'),
        ),
        migrations.AddField(
            model_name='drctrequest',
            name='fk_drct_severity',
            field=models.ForeignKey(db_column='fk_drct_severity', on_delete=django.db.models.deletion.DO_NOTHING, to='ct_requests.drctseverity'),
        ),
        migrations.CreateModel(
            name='DRCTStudentRequest',
            fields=[
                ('pk_drct_student_request', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fk_drct_request', models.ForeignKey(db_column='fk_drct_request', on_delete=django.db.models.deletion.DO_NOTHING, to='ct_requests.drctrequest')),
                ('fk_student', models.ForeignKey(db_column='fk_student', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_drct_student_request',
            },
        ),
    ]
