# Generated by Django 5.0.4 on 2024-05-21 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drctparagraph',
            name='fk_drct_section',
            field=models.ForeignKey(db_column='fk_drct_section', on_delete=django.db.models.deletion.CASCADE, to='ct_requests.drctsection'),
        ),
        migrations.AlterField(
            model_name='drctsection',
            name='fk_drct_chapter',
            field=models.ForeignKey(db_column='fk_drct_chapter', on_delete=django.db.models.deletion.CASCADE, to='ct_requests.drctchapter'),
        ),
    ]
