# Generated by Django 5.0.4 on 2024-06-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drctinternalnote',
            name='ctdr_cmdt_answer',
            field=models.IntegerField(null=True),
        ),
    ]
