# Generated by Django 5.0.4 on 2024-05-24 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_requests', '0002_alter_drctparagraph_fk_drct_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRCTTitle',
            fields=[
                ('pk_drct_title', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_drct_title',
            },
        ),
        migrations.AddField(
            model_name='drctsection',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='DRCTSeverityItem',
            fields=[
                ('pk_drct_severity_item', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('fk_drct_severit', models.ForeignKey(db_column='fk_drct_severity', on_delete=django.db.models.deletion.CASCADE, to='ct_requests.drctseverity')),
            ],
            options={
                'db_table': 'tb_drct_severity_item',
            },
        ),
        migrations.AddField(
            model_name='drctchapter',
            name='fk_drct_title',
            field=models.ForeignKey(db_column='fk_drct_title', default=0, on_delete=django.db.models.deletion.CASCADE, to='ct_requests.drcttitle'),
        ),
    ]
