# Generated by Django 5.0.4 on 2024-05-24 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_requests', '0003_drcttitle_drctsection_value_drctseverityitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drctchapter',
            name='fk_drct_title',
            field=models.ForeignKey(db_column='fk_drct_title', on_delete=django.db.models.deletion.CASCADE, to='ct_requests.drcttitle'),
        ),
    ]
